export const tr = {
  app: {
    title: "PlanDraw Operatör",
    subtitle: "İnşaat planı → robot komutları → güvenli çalıştırma",
    badge: "V3 Deneme",
  },
  dashboard: {
    backend: "Backend Aktif",
    robot: "Robot Bağlantısı",
    plan: "Plan Hazırlığı",
    safety: "Güvenlik / STOP",
    lastRun: "Son Çalıştırma",
  },
  upload: {
    title: "Plan Yükleme",
    hint: "DXF önerilen formattır. DWG doğrudan desteklenmez; önce DXF'e dönüştürülmelidir.",
    drop: "Dosyayı sürükleyip bırakın veya tıklayarak seçin",
    formats: "Desteklenen: .dxf, .json (normalize plan)",
    prepare: "Planı Hazırla",
    compile: "Metinden Derle",
    noFile: "Henüz dosya seçilmedi",
  },
  compile: {
    title: "Çizim Hazırlığı",
    commandCount: "Komut sayısı",
    strokeCount: "Tahmini stroke",
    penSafe: "Pen-safe derleme",
    penSafeOk: "Kopuk çizgiler arasında kalem yukarı kalkar (yazılım garantisi).",
    penSafeWarn: "Komut listesi pen-safe doğrulamasından geçemedi veya henüz derlenmedi.",
    success: "Plan başarıyla komutlara dönüştürüldü.",
    error: "Derleme hatası",
    idle: "Plan yükleyin veya metin derleyin.",
  },
  robot: {
    title: "Robot Kontrol",
    dryRun: "Dry-run Çalıştır",
    simulate: "Simülasyon Başlat",
    live: "Canlı Robota Gönder",
    stop: "Robotu Durdur (Canlı STOP)",
    stopHint: "Bu yazılımsal STOP fiziksel acil stop'un yerini tutmaz.",
    simStop: "Simülasyonu Durdur",
    needsCommands: "Önce plan derlenmeli.",
    busy: "İşlem sürüyor…",
  },
  log: {
    title: "Komut / Log",
    empty: "Henüz komut veya log yok.",
    lastError: "Son hata",
    lastSuccess: "Son başarılı işlem",
  },
  preview: {
    title: "Plan Önizleme",
    placeholder: "Önizleme alanı — ileride SVG/canvas genişletilebilir.",
    points: "Yol noktası",
  },
  safety: {
    banner: "Güvenlik: Canlı çalıştırma yalnızca hazır ortamda ve operatör gözetiminde yapılmalıdır.",
  },
  status: {
    online: "Bağlı",
    offline: "Bağlantı yok",
    checking: "Kontrol ediliyor…",
    ready: "Hazır",
    waiting: "Bekliyor",
    error: "Hata",
    unknown: "Bilinmiyor",
  },
} as const;
